# Generated by Django 4.1.5 on 2023-01-19 13:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudyapp', '0003_alter_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='cc',
            field=cloudinary.models.CloudinaryField(default=89, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
