# Generated by Django 4.1.5 on 2023-01-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudyapp', '0005_remove_photos_id_alter_photos_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
